
<!--command -->
var ON="ON";
var OFF="OFF";
var OPEN="OPEN";
var CLOSE="CLOSE";
var UP="UP";
var DOWN="DOWN";

var none="null";
var time;

<!--STATE-->
var STATE_LIGHT_LIV;
var STATE_LIGHT_BATH;
var STATE_LIGHT_OUT;
var STATE_LIGHT_KIT;
var STATE_WEATHER1;
var STATE_WEATHER2;
var STATE_WEATHER3;
var STATE_WEATHER4;
var STATE_WEATHER5;
var STATE_BOX;
var BOX_PW;
var BOX_ERR;
var STATE_GAS;
var STATE_CUTTON;
var STATE_WINDOW;
var STATE_DEVICE=0;
var DEV_LIV="LIV",
DEV_BAT="BAT",
DEV_KIT="KIT",
DEV_OUT="OUT",
DEV_GAS="GAS",
DEV_LIGHT_ALL="ALL"
DEV_WINDOW="WINDOW",
DEV_CUTTON="CUTTON",
DEV_WEATHER="WEATHER"
